# Generated by Django 6.0.3 on 2026-05-14 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_like_user_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], default=1, verbose_name='Значение голоса'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_correct_for_questions', to='questions.answer', verbose_name='Правильный ответ'),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], default=1, verbose_name='Значение голоса'),
        ),
    ]
