# Generated by Django 6.0.5 on 2026-05-27 19:40

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_vote_value_and_correct_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('title', config='simple', weight='A'), '||', django.contrib.postgres.search.SearchVector('text', config='simple', weight='B'), None), name='question_search_gin_idx'),
        ),
    ]
