worker_processes auto;
events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    gzip on;
    gzip_types text/plain text/css application/javascript image/jpeg image/png;

    upstream edu_backend {
        server 127.0.0.1:8000;
        server 127.0.0.1:8001;
        server 127.0.0.1:8002;
        server 127.0.0.1:8003;
        server 127.0.0.1:8004;
        server 127.0.0.1:8005;
    }

    proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=proxy_cache:10m max_size=1g inactive=60m;

    server {
        listen 80;
        server_name localhost;

        location /static/ {
            alias "/home/xah7p/Рабочий стол/VK-EDU/WEB/static_collected/";
            expires 30d;
            add_header Cache-Control "public";
        }

        location /uploads/ {
            alias "/home/xah7p/Рабочий стол/VK-EDU/WEB/uploads/";
            expires 30d;
            add_header Cache-Control "public";
        }

        location / {
            proxy_pass http://edu_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_cache proxy_cache;
            proxy_cache_valid 200 10m;
            add_header X-Cache-Status $upstream_cache_status;
        }
    }
}